#!/bin/bash
# Build script generated by configure — uses top-level Makefile

set -e

if [ ! -f "config.mk" ]; then
    echo "Error: configuration not found. Run ./configure first."
    exit 1
fi

# Invoke top-level Makefile which includes config.mk
make -j$(nproc) "$@"
