#!/bin/bash
# Build script generated by configure

set -e

if [ ! -d "build" ]; then
    echo "Error: build directory not found. Run ./configure first."
    exit 1
fi

cd build
make -j$(nproc) "$@"
cd ..
