# Configuration file generated by configure script
# This file is sourced by Makefiles

PREFIX=/usr/local
BUILD_TYPE=Release

# Feature flags
USE_MPI=1
USE_PAPI=1

# Library build options
BUILD_SHARED_LIBS=1
BUILD_STATIC_LIBS=1

# Compiler flags based on build type
ifeq ($(BUILD_TYPE),Debug)
    CFLAGS += -fPIC -Wall -g -O0 -DPERF_DEBUG=1
    FCFLAGS += -fPIC -Wall -g -O0 -DPERF_DEBUG=1
else
    CFLAGS += -fPIC -Wall -O2 -DPERF_DEBUG=0
    FCFLAGS += -fPIC -Wall -O2 -DPERF_DEBUG=0
endif

# Environment-specific settings



# Export variables for use in sub-makefiles
export PREFIX USE_MPI USE_PAPI BUILD_SHARED_LIBS BUILD_STATIC_LIBS
