#!/bin/bash
# Install script generated by configure

set -e

if [ ! -d "build" ]; then
    echo "Error: build directory not found. Run ./configure and build first."
    exit 1
fi

cd build
make install "$@"
cd ..
