#!/bin/bash
# Install script generated by configure

set -e

if [ ! -f "config.mk" ]; then
    echo "Error: configuration not found. Run ./configure and build first."
    exit 1
fi

# Source configuration  
source config.mk

make install "$@"
