#!/bin/bash
# Install script generated by configure — uses top-level Makefile

set -e

if [ ! -f "config.mk" ]; then
    echo "Error: configuration not found. Run ./configure and build first."
    exit 1
fi

# Invoke install via top-level Makefile
make install "$@"
