
# Include configuration to get PREFIX
-include ../../config.mk
-include ../config.mk

# Use installation prefix for library paths - fallback if PREFIX not set
PREFIX ?= /usr/local
LIBDIR = $(PREFIX)/lib

# MPI settings - default to match src/Makefile
USE_MPI ?= 1
ifeq ($(USE_MPI),1)
LIB_SUFFIX_MPI = _mpi
else
LIB_SUFFIX_MPI = 
endif

# PAPI settings - default to match src/Makefile
USE_PAPI ?= 1
ifeq ($(USE_PAPI),1)
LIB_SUFFIX_PAPI = _papi
else
LIB_SUFFIX_PAPI = 
endif

LIB_SUFFIX = $(LIB_SUFFIX_PAPI)$(LIB_SUFFIX_MPI)
LIB_SUFFIX_FORT = $(LIB_SUFFIX_PAPI)$(LIB_SUFFIX_MPI)_fort

# perf_regions library from installation prefix, with RPATH for runtime resolution
# We use abspath to ensure validity regardless of where make is run from (assuming relative depth is consistent)
BUILD_DIR_REL := ../../build
BUILD_DIR := $(abspath $(BUILD_DIR_REL))

# Define PERFREGION flags
PERFREGION_CFLAGS := -I../../src $(PAPI_CFLAGS)
PERFREGION_FFLAGS := -I../../src $(PAPI_CFLAGS)

PERFREGION_LDFLAGS := -L../../build -lperf_regions${LIB_SUFFIX} $(PAPI_LDFLAGS)
PERFREGION_LDFLAGS_FORT := -L../../build -lperf_regions${LIB_SUFFIX_FORT} $(PAPI_LDFLAGS)

# Add PAPI flags if enabled
ifeq ($(USE_PAPI),1)
    PERFREGION_CFLAGS += $(PAPI_CFLAGS)
    PERFREGION_LDFLAGS += $(PAPI_LDFLAGS)
endif
