
# Include configuration to get PREFIX
ifneq ("$(wildcard ../config_tests.mk)","")
# Use configuration from testing framework if it exists
$(info Using '../config_tests.mk')
include ../config_tests.mk
else
# This is for non-test runs
include ../../config.mk
$(info Using '../../config.mk')
endif

# Use installation prefix for library paths - fallback if PREFIX not set
PREFIX ?= /usr/local
LIBDIR = $(PREFIX)/lib

# MPI settings - default to match src/Makefile
USE_MPI ?= 1
ifeq ($(USE_MPI),1)
LIB_SUFFIX_MPI = _mpi
else
LIB_SUFFIX_MPI = 
endif

# PAPI settings - default to match src/Makefile
USE_PAPI ?= 1
ifeq ($(USE_PAPI),1)
LIB_SUFFIX_PAPI = _papi
else
LIB_SUFFIX_PAPI = 
endif

LIB_SUFFIX = $(LIB_SUFFIX_PAPI)$(LIB_SUFFIX_MPI)
LIB_SUFFIX_FORT = $(LIB_SUFFIX_PAPI)$(LIB_SUFFIX_MPI)_fort

# perf_regions library from installation prefix, with RPATH for runtime resolution
# We use abspath to ensure validity regardless of where make is run from (assuming relative depth is consistent)
BUILD_DIR_REL := ../../build
BUILD_DIR := $(abspath $(BUILD_DIR_REL))

# Define PERFREGION flags
PERFREGION_CFLAGS := -I../../src
PERFREGION_FFLAGS := -I../../src

PERFREGION_LDFLAGS := -L../../build -lperf_regions$(LIB_SUFFIX)
PERFREGION_LDFLAGS_FORT := -L../../build -lperf_regions$(LIB_SUFFIX_FORT)

# Add PAPI flags if enabled
ifeq ($(USE_PAPI),1)
    PERFREGION_CFLAGS += $(PAPI_CFLAGS)
    PERFREGION_FFLAGS += $(PAPI_CFLAGS)
    PERFREGION_LDFLAGS += $(PAPI_LDFLAGS)
    PERFREGION_LDFLAGS_FORT += $(PAPI_LDFLAGS)
endif

$(info ===================================================)
$(info USE_MPI: $(USE_MPI))
$(info USE_PAPI: $(USE_PAPI))
$(info PERFREGION_CFLAGS: $(PERFREGION_CFLAGS))
$(info PERFREGION_FFLAGS: $(PERFREGION_FFLAGS))
$(info PERFREGION_LDFLAGS: $(PERFREGION_LDFLAGS))
$(info PERFREGION_LDFLAGS_FORT: $(PERFREGION_LDFLAGS_FORT))
$(info ===================================================)
