all:
	make -C array_test_c
	make -C array_test_f
	make -C stream_benchmark
	make -C nemo_test_f


clean:
	make -C array_test_c clean
	make -C array_test_f clean
	make -C stream_benchmark clean
	make -C nemo_test_f clean
